ASSUME	CS:CGR,DS:CGR
CGR	GROUP	COD,DAT
COD	SEGMENT	BYTE
ORG	100H
HLP1	PROC	NEAR
	MOV	SP,100H
	PUSH	CS
	POP	DS
	MOV	SI,80H
	PUSH	CS
	POP	ES
	MOV	AH,'/'
	CALL	READ_FILE_STRING
	JC	WRITE_ERROR
	INT	20H
WRITE_ERROR:
	DEC	AX
	LEA	SI,NONE_STRING_
	OR	AX,AX
	JZ	PRINT_ERROR
	LEA	SI,NONE_COMMAND_
PRINT_ERROR:
	MOV	AH,3
	XOR	BH,BH
	INT	10H
	XOR	CH,CH
	MOV	CL,DH
	XOR	DH,DH
	MOV	[X],DX
	MOV	[Y],CX
	CALL	WRITE_WORD
	INT	20H
ENDP
include	readFSTR.lib
INCLUDE WRWORD.LIB
INCLUDE	WRITESYM.LIB
ENDS
DAT	SEGMENT	BYTE
NONE_COMMAND_	DB	'None File',0
NONE_STRING_	DB	'None String',0
ENDS
END	HLP1
