ASSUME	CS:CGR,DS:CGR
CGR	GROUP	COD,DAT
COD	SEGMENT	BYTE
ORG	100H
HLP1	PROC	NEAR
	PUSH	CS
	POP	DS
	MOV	SI,80H
	PUSH	CS
	POP	ES
	LEA	AX,FIRST_
	LEA	BX,SECOND_
	LEA	DX,NEW_
	CALL	READ_LINE
	JC	WRITE_ERROR
	INT	20H
WRITE_ERROR:
	DEC	AX
	LEA	SI,NONE_COMMAND_
	OR	AX,AX
	JZ	PRINT_ERROR
	DEC	AX
	LEA	SI,REPEAT_USE_COMMAND_
	OR	AX,AX
	JZ	PRINT_ERROR
	DEC	AX
	LEA	SI,ABSENT_SYMBOL_OF_BEGIN_COMMAND_
	OR	AX,AX
	JZ	PRINT_ERROR
	DEC	AX
	LEA	SI,NONE_STRING_
	OR	AX,AX
	JZ	PRINT_ERROR
	DEC	AX
	LEA	SI,UNRECOGNIZEBLE_SYMBOL_
	OR	AX,AX
	JZ	PRINT_ERROR
	DEC	AX
	LEA	SI,UNNECESSARY_COMMAND_
	OR	AX,AX
	JZ	PRINT_ERROR
	DEC	AX
	LEA	SI,UNNECESSARY_SWITCH_
PRINT_ERROR:
	MOV	AH,3
	XOR	BH,BH
	INT	10H
	XOR	CH,CH
	MOV	CL,DH
	XOR	DH,DH
	MOV	[X],DX
	MOV	[Y],CX
	CALL	WRITE_WORD
	INT	20H
ENDP
include	readline.lib
INCLUDE WRWORD.LIB
INCLUDE	WRITESYM.LIB
ENDS
DAT	SEGMENT	BYTE
NONE_COMMAND_	DB	'None command',0
REPEAT_USE_COMMAND_	DB	'Repeat using command',0
ABSENT_SYMBOL_OF_BEGIN_COMMAND_	DB	'Absent symbol of begin command',0
NONE_STRING_	DB	'None string',0
UNRECOGNIZEBLE_SYMBOL_	DB	'Unrecognizeble symbol',0
UNNECESSARY_COMMAND_	DB	'Unnecessary command',0
UNNECESSARY_SWITCH_	DB	'Unnecessary switch',0
FIRST_	DB	'/XYZ',0FFH
SECOND_	DB	'XABC',0FEH,'ZW',0FFH
NEW_	DW	3	DUP	(0)
ENDS
END	HLP1
